### ISSUE TITLE
Error when react-theming tries to import Hue type

### ISSUE THREAD

**Issue by toddoglethorpe** [zendeskgarden/react-components#677]
Thanks for these great looking components. I'm getting an error from `react-theming` when building my project, however.

## Reality

A project using `@zendeskgarden/react-theming` will not build with `tsc` (TS 3.8.3). Instead, an error message about importing from `styled-components` occurs:

```
node_modules/@zendeskgarden/react-theming/dist/typings/utils/getColor.d.ts:7:24 - error TS2614: Module '"../../../../../@types/styled-components/ts3.7"' has no exported member 'Hue'. Did you mean to use 'import Hue from "../../../../../@types/styled-components/ts3.7"' instead?

7 import { DefaultTheme, Hue } from 'styled-components';
```

## Steps to Reproduce

There is [this minimal demonstration repo](https://github.com/toddoglethorpe/zengarden-issue).

But the short story is:

add
- `typescript`
- `@zendeskgarden/react-theming`
- `styled-components`
- `@types/styled-components` 

to a project. Import `ThemeProvider` from `react-theming` and try to compile (run `tsc`). Error occurs with `styled-components` v4 and v5.

### Fine Print

- Component: react-theming
- Version: 8.2.0
- Browsers: not there yet

Thanks!

**Comment by austin94** [comment]
Thanks for finding this. It looks like this is specific to the `Hue` value [we supply when we override the `DefaultTheme` value](https://styled-components.com/docs/api#create-a-declarations-file).

For a short-term fix you can add a type definition file similar to https://github.com/zendeskgarden/react-components/blob/master/utils/build/styled.d.ts to ensure that the `theme` value is typed correctly.

For a full fix we will need to remove that `Hue` import and either replicate the type locally or move to `any` usages.

**Comment by austin94** [comment]
@toddoglethorpe this has been merged and will be released as a patch for `react-theming` on Wednesday with our scheduled release. Let us know if you run into any other TS issues.

**Comment by toddoglethorpe** [comment]
Great, thanks for the quick response!
